# Generated by Django 5.2.15 on 2026-06-15 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('zoho', 'Zoho'), ('sharepoint', 'SharePoint'), ('google_drive', 'Google Drive'), ('other', 'Other')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-synced_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('zoho', 'Zoho'), ('sharepoint', 'SharePoint'), ('google_drive', 'Google Drive'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pos_order_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_orders', to='orders.inboundorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
